// @generated by protoc-gen-es v1.10.0
// @generated from file model/common.proto (package proto.model, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message proto.model.Model
 */
export declare class Model extends Message<Model> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 3;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 4;
   */
  deletedAt?: Timestamp;

  constructor(data?: PartialMessage<Model>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "proto.model.Model";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Model;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Model;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Model;

  static equals(a: Model | PlainMessage<Model> | undefined, b: Model | PlainMessage<Model> | undefined): boolean;
}

