// @generated by protoc-gen-es v1.10.0
// @generated from file common.proto (package proto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum proto.Operator
 */
export const Operator = /*@__PURE__*/ proto3.makeEnum(
  "proto.Operator",
  [
    {no: 0, name: "AND"},
    {no: 1, name: "OR"},
  ],
);

/**
 * @generated from message proto.Empty
 */
export const Empty = /*@__PURE__*/ proto3.makeMessageType(
  "proto.Empty",
  [],
);

/**
 * @generated from message proto.ListOption
 */
export const ListOption = /*@__PURE__*/ proto3.makeMessageType(
  "proto.ListOption",
  () => [
    { no: 1, name: "pager", kind: "message", T: Pager, opt: true },
    { no: 2, name: "sorters", kind: "message", T: Sorter, repeated: true },
    { no: 3, name: "filterGroup", kind: "message", T: FilterGroup, opt: true },
  ],
);

/**
 * @generated from message proto.Pager
 */
export const Pager = /*@__PURE__*/ proto3.makeMessageType(
  "proto.Pager",
  () => [
    { no: 1, name: "number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message proto.Sorter
 */
export const Sorter = /*@__PURE__*/ proto3.makeMessageType(
  "proto.Sorter",
  () => [
    { no: 1, name: "ascending", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "field", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message proto.Filter
 */
export const Filter = /*@__PURE__*/ proto3.makeMessageType(
  "proto.Filter",
  () => [
    { no: 1, name: "field", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "fuzzy", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * Group of filters with a logical operator.
 *
 * @generated from message proto.FilterGroup
 */
export const FilterGroup = /*@__PURE__*/ proto3.makeMessageType(
  "proto.FilterGroup",
  () => [
    { no: 1, name: "operator", kind: "enum", T: proto3.getEnumType(Operator) },
    { no: 2, name: "filters", kind: "message", T: Filter, repeated: true },
    { no: 3, name: "nestedGroups", kind: "message", T: FilterGroup, repeated: true },
  ],
);

