// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: main.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import * as _m0 from "protobufjs/minimal";
import { Empty, ListOption } from "./common";
import { Role } from "./model/role";
import Long = require("long");

export const protobufPackage = "proto";

export interface CreateAccountRequest {
  UserName: string;
  Password: string;
  DisplayName: string;
}

export interface ListAccountRequest {
  Option?: ListOption | undefined;
}

export interface ListAccountResponse {
  List: AccountData[];
  Total: number;
}

export interface AccountData {
  UserName: string;
  DisplayName: string;
  Email: string;
  State: number;
}

export interface UpdateAccountRequest {
  ID: string;
  DisplayName: string;
  /** 0: no change, 1: active, 2: inactive */
  State: number;
}

export interface DeleteAccountRequest {
  ID: string;
  Page: Page | undefined;
}

export interface CreateRoleRequest {
  Name: string;
  Page: Page | undefined;
}

export interface Page {
  AccountList: PageOperation | undefined;
  Role: PageOperation | undefined;
  Setting: PageOperation | undefined;
}

export interface PageOperation {
  Create: boolean;
  Read: boolean;
  Update: boolean;
  Delete: boolean;
}

export interface ListRoleRequest {
  Option?: ListOption | undefined;
}

export interface ListRoleResponse {
  List: RoleData[];
  Total: number;
}

export interface RoleData {
  ID: string;
  Name: string;
}

export interface GetRoleAuthRequest {
  /** if ID is "", return auth based on session */
  ID?: string | undefined;
}

export interface GetRoleAuthResponse {
  Page: Page | undefined;
}

export interface UpdateRoleRequest {
  ID: string;
  Name: string;
  Page: Page | undefined;
}

export interface DeleteRoleRequest {
  ID: string;
}

export interface BindRoleRequest {
  AccountID: string;
  RoleID: string;
}

export interface UnBindRoleRequest {
  AccountID: string;
}

export interface LoginRequest {
  UserName: string;
  Password: string;
}

export interface LoginResponse {
  SessionID: string;
  Role: Role | undefined;
}

export interface LogoutRequest {
  SessionID: string;
}

function createBaseCreateAccountRequest(): CreateAccountRequest {
  return { UserName: "", Password: "", DisplayName: "" };
}

export const CreateAccountRequest = {
  encode(message: CreateAccountRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.UserName !== "") {
      writer.uint32(10).string(message.UserName);
    }
    if (message.Password !== "") {
      writer.uint32(18).string(message.Password);
    }
    if (message.DisplayName !== "") {
      writer.uint32(26).string(message.DisplayName);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateAccountRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.UserName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Password = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.DisplayName = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateAccountRequest {
    return {
      UserName: isSet(object.UserName) ? globalThis.String(object.UserName) : "",
      Password: isSet(object.Password) ? globalThis.String(object.Password) : "",
      DisplayName: isSet(object.DisplayName) ? globalThis.String(object.DisplayName) : "",
    };
  },

  toJSON(message: CreateAccountRequest): unknown {
    const obj: any = {};
    if (message.UserName !== "") {
      obj.UserName = message.UserName;
    }
    if (message.Password !== "") {
      obj.Password = message.Password;
    }
    if (message.DisplayName !== "") {
      obj.DisplayName = message.DisplayName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateAccountRequest>, I>>(base?: I): CreateAccountRequest {
    return CreateAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateAccountRequest>, I>>(object: I): CreateAccountRequest {
    const message = createBaseCreateAccountRequest();
    message.UserName = object.UserName ?? "";
    message.Password = object.Password ?? "";
    message.DisplayName = object.DisplayName ?? "";
    return message;
  },
};

function createBaseListAccountRequest(): ListAccountRequest {
  return { Option: undefined };
}

export const ListAccountRequest = {
  encode(message: ListAccountRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Option !== undefined) {
      ListOption.encode(message.Option, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListAccountRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Option = ListOption.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAccountRequest {
    return { Option: isSet(object.Option) ? ListOption.fromJSON(object.Option) : undefined };
  },

  toJSON(message: ListAccountRequest): unknown {
    const obj: any = {};
    if (message.Option !== undefined) {
      obj.Option = ListOption.toJSON(message.Option);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAccountRequest>, I>>(base?: I): ListAccountRequest {
    return ListAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAccountRequest>, I>>(object: I): ListAccountRequest {
    const message = createBaseListAccountRequest();
    message.Option = (object.Option !== undefined && object.Option !== null)
      ? ListOption.fromPartial(object.Option)
      : undefined;
    return message;
  },
};

function createBaseListAccountResponse(): ListAccountResponse {
  return { List: [], Total: 0 };
}

export const ListAccountResponse = {
  encode(message: ListAccountResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.List) {
      AccountData.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.Total !== 0) {
      writer.uint32(16).int64(message.Total);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListAccountResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAccountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.List.push(AccountData.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Total = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAccountResponse {
    return {
      List: globalThis.Array.isArray(object?.List) ? object.List.map((e: any) => AccountData.fromJSON(e)) : [],
      Total: isSet(object.Total) ? globalThis.Number(object.Total) : 0,
    };
  },

  toJSON(message: ListAccountResponse): unknown {
    const obj: any = {};
    if (message.List?.length) {
      obj.List = message.List.map((e) => AccountData.toJSON(e));
    }
    if (message.Total !== 0) {
      obj.Total = Math.round(message.Total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAccountResponse>, I>>(base?: I): ListAccountResponse {
    return ListAccountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAccountResponse>, I>>(object: I): ListAccountResponse {
    const message = createBaseListAccountResponse();
    message.List = object.List?.map((e) => AccountData.fromPartial(e)) || [];
    message.Total = object.Total ?? 0;
    return message;
  },
};

function createBaseAccountData(): AccountData {
  return { UserName: "", DisplayName: "", Email: "", State: 0 };
}

export const AccountData = {
  encode(message: AccountData, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.UserName !== "") {
      writer.uint32(10).string(message.UserName);
    }
    if (message.DisplayName !== "") {
      writer.uint32(18).string(message.DisplayName);
    }
    if (message.Email !== "") {
      writer.uint32(26).string(message.Email);
    }
    if (message.State !== 0) {
      writer.uint32(32).int32(message.State);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AccountData {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.UserName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.DisplayName = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Email = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.State = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountData {
    return {
      UserName: isSet(object.UserName) ? globalThis.String(object.UserName) : "",
      DisplayName: isSet(object.DisplayName) ? globalThis.String(object.DisplayName) : "",
      Email: isSet(object.Email) ? globalThis.String(object.Email) : "",
      State: isSet(object.State) ? globalThis.Number(object.State) : 0,
    };
  },

  toJSON(message: AccountData): unknown {
    const obj: any = {};
    if (message.UserName !== "") {
      obj.UserName = message.UserName;
    }
    if (message.DisplayName !== "") {
      obj.DisplayName = message.DisplayName;
    }
    if (message.Email !== "") {
      obj.Email = message.Email;
    }
    if (message.State !== 0) {
      obj.State = Math.round(message.State);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountData>, I>>(base?: I): AccountData {
    return AccountData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountData>, I>>(object: I): AccountData {
    const message = createBaseAccountData();
    message.UserName = object.UserName ?? "";
    message.DisplayName = object.DisplayName ?? "";
    message.Email = object.Email ?? "";
    message.State = object.State ?? 0;
    return message;
  },
};

function createBaseUpdateAccountRequest(): UpdateAccountRequest {
  return { ID: "", DisplayName: "", State: 0 };
}

export const UpdateAccountRequest = {
  encode(message: UpdateAccountRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== "") {
      writer.uint32(10).string(message.ID);
    }
    if (message.DisplayName !== "") {
      writer.uint32(18).string(message.DisplayName);
    }
    if (message.State !== 0) {
      writer.uint32(24).int32(message.State);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UpdateAccountRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.DisplayName = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.State = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateAccountRequest {
    return {
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      DisplayName: isSet(object.DisplayName) ? globalThis.String(object.DisplayName) : "",
      State: isSet(object.State) ? globalThis.Number(object.State) : 0,
    };
  },

  toJSON(message: UpdateAccountRequest): unknown {
    const obj: any = {};
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.DisplayName !== "") {
      obj.DisplayName = message.DisplayName;
    }
    if (message.State !== 0) {
      obj.State = Math.round(message.State);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateAccountRequest>, I>>(base?: I): UpdateAccountRequest {
    return UpdateAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateAccountRequest>, I>>(object: I): UpdateAccountRequest {
    const message = createBaseUpdateAccountRequest();
    message.ID = object.ID ?? "";
    message.DisplayName = object.DisplayName ?? "";
    message.State = object.State ?? 0;
    return message;
  },
};

function createBaseDeleteAccountRequest(): DeleteAccountRequest {
  return { ID: "", Page: undefined };
}

export const DeleteAccountRequest = {
  encode(message: DeleteAccountRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== "") {
      writer.uint32(10).string(message.ID);
    }
    if (message.Page !== undefined) {
      Page.encode(message.Page, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeleteAccountRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Page = Page.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAccountRequest {
    return {
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      Page: isSet(object.Page) ? Page.fromJSON(object.Page) : undefined,
    };
  },

  toJSON(message: DeleteAccountRequest): unknown {
    const obj: any = {};
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.Page !== undefined) {
      obj.Page = Page.toJSON(message.Page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteAccountRequest>, I>>(base?: I): DeleteAccountRequest {
    return DeleteAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteAccountRequest>, I>>(object: I): DeleteAccountRequest {
    const message = createBaseDeleteAccountRequest();
    message.ID = object.ID ?? "";
    message.Page = (object.Page !== undefined && object.Page !== null) ? Page.fromPartial(object.Page) : undefined;
    return message;
  },
};

function createBaseCreateRoleRequest(): CreateRoleRequest {
  return { Name: "", Page: undefined };
}

export const CreateRoleRequest = {
  encode(message: CreateRoleRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Name !== "") {
      writer.uint32(10).string(message.Name);
    }
    if (message.Page !== undefined) {
      Page.encode(message.Page, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateRoleRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Page = Page.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateRoleRequest {
    return {
      Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
      Page: isSet(object.Page) ? Page.fromJSON(object.Page) : undefined,
    };
  },

  toJSON(message: CreateRoleRequest): unknown {
    const obj: any = {};
    if (message.Name !== "") {
      obj.Name = message.Name;
    }
    if (message.Page !== undefined) {
      obj.Page = Page.toJSON(message.Page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateRoleRequest>, I>>(base?: I): CreateRoleRequest {
    return CreateRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateRoleRequest>, I>>(object: I): CreateRoleRequest {
    const message = createBaseCreateRoleRequest();
    message.Name = object.Name ?? "";
    message.Page = (object.Page !== undefined && object.Page !== null) ? Page.fromPartial(object.Page) : undefined;
    return message;
  },
};

function createBasePage(): Page {
  return { AccountList: undefined, Role: undefined, Setting: undefined };
}

export const Page = {
  encode(message: Page, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AccountList !== undefined) {
      PageOperation.encode(message.AccountList, writer.uint32(10).fork()).ldelim();
    }
    if (message.Role !== undefined) {
      PageOperation.encode(message.Role, writer.uint32(18).fork()).ldelim();
    }
    if (message.Setting !== undefined) {
      PageOperation.encode(message.Setting, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Page {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.AccountList = PageOperation.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Role = PageOperation.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Setting = PageOperation.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Page {
    return {
      AccountList: isSet(object.AccountList) ? PageOperation.fromJSON(object.AccountList) : undefined,
      Role: isSet(object.Role) ? PageOperation.fromJSON(object.Role) : undefined,
      Setting: isSet(object.Setting) ? PageOperation.fromJSON(object.Setting) : undefined,
    };
  },

  toJSON(message: Page): unknown {
    const obj: any = {};
    if (message.AccountList !== undefined) {
      obj.AccountList = PageOperation.toJSON(message.AccountList);
    }
    if (message.Role !== undefined) {
      obj.Role = PageOperation.toJSON(message.Role);
    }
    if (message.Setting !== undefined) {
      obj.Setting = PageOperation.toJSON(message.Setting);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Page>, I>>(base?: I): Page {
    return Page.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Page>, I>>(object: I): Page {
    const message = createBasePage();
    message.AccountList = (object.AccountList !== undefined && object.AccountList !== null)
      ? PageOperation.fromPartial(object.AccountList)
      : undefined;
    message.Role = (object.Role !== undefined && object.Role !== null)
      ? PageOperation.fromPartial(object.Role)
      : undefined;
    message.Setting = (object.Setting !== undefined && object.Setting !== null)
      ? PageOperation.fromPartial(object.Setting)
      : undefined;
    return message;
  },
};

function createBasePageOperation(): PageOperation {
  return { Create: false, Read: false, Update: false, Delete: false };
}

export const PageOperation = {
  encode(message: PageOperation, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Create !== false) {
      writer.uint32(8).bool(message.Create);
    }
    if (message.Read !== false) {
      writer.uint32(16).bool(message.Read);
    }
    if (message.Update !== false) {
      writer.uint32(24).bool(message.Update);
    }
    if (message.Delete !== false) {
      writer.uint32(32).bool(message.Delete);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PageOperation {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePageOperation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Create = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Read = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Update = reader.bool();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Delete = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PageOperation {
    return {
      Create: isSet(object.Create) ? globalThis.Boolean(object.Create) : false,
      Read: isSet(object.Read) ? globalThis.Boolean(object.Read) : false,
      Update: isSet(object.Update) ? globalThis.Boolean(object.Update) : false,
      Delete: isSet(object.Delete) ? globalThis.Boolean(object.Delete) : false,
    };
  },

  toJSON(message: PageOperation): unknown {
    const obj: any = {};
    if (message.Create !== false) {
      obj.Create = message.Create;
    }
    if (message.Read !== false) {
      obj.Read = message.Read;
    }
    if (message.Update !== false) {
      obj.Update = message.Update;
    }
    if (message.Delete !== false) {
      obj.Delete = message.Delete;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PageOperation>, I>>(base?: I): PageOperation {
    return PageOperation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PageOperation>, I>>(object: I): PageOperation {
    const message = createBasePageOperation();
    message.Create = object.Create ?? false;
    message.Read = object.Read ?? false;
    message.Update = object.Update ?? false;
    message.Delete = object.Delete ?? false;
    return message;
  },
};

function createBaseListRoleRequest(): ListRoleRequest {
  return { Option: undefined };
}

export const ListRoleRequest = {
  encode(message: ListRoleRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Option !== undefined) {
      ListOption.encode(message.Option, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListRoleRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Option = ListOption.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListRoleRequest {
    return { Option: isSet(object.Option) ? ListOption.fromJSON(object.Option) : undefined };
  },

  toJSON(message: ListRoleRequest): unknown {
    const obj: any = {};
    if (message.Option !== undefined) {
      obj.Option = ListOption.toJSON(message.Option);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListRoleRequest>, I>>(base?: I): ListRoleRequest {
    return ListRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListRoleRequest>, I>>(object: I): ListRoleRequest {
    const message = createBaseListRoleRequest();
    message.Option = (object.Option !== undefined && object.Option !== null)
      ? ListOption.fromPartial(object.Option)
      : undefined;
    return message;
  },
};

function createBaseListRoleResponse(): ListRoleResponse {
  return { List: [], Total: 0 };
}

export const ListRoleResponse = {
  encode(message: ListRoleResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.List) {
      RoleData.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.Total !== 0) {
      writer.uint32(16).int64(message.Total);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListRoleResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListRoleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.List.push(RoleData.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Total = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListRoleResponse {
    return {
      List: globalThis.Array.isArray(object?.List) ? object.List.map((e: any) => RoleData.fromJSON(e)) : [],
      Total: isSet(object.Total) ? globalThis.Number(object.Total) : 0,
    };
  },

  toJSON(message: ListRoleResponse): unknown {
    const obj: any = {};
    if (message.List?.length) {
      obj.List = message.List.map((e) => RoleData.toJSON(e));
    }
    if (message.Total !== 0) {
      obj.Total = Math.round(message.Total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListRoleResponse>, I>>(base?: I): ListRoleResponse {
    return ListRoleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListRoleResponse>, I>>(object: I): ListRoleResponse {
    const message = createBaseListRoleResponse();
    message.List = object.List?.map((e) => RoleData.fromPartial(e)) || [];
    message.Total = object.Total ?? 0;
    return message;
  },
};

function createBaseRoleData(): RoleData {
  return { ID: "", Name: "" };
}

export const RoleData = {
  encode(message: RoleData, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== "") {
      writer.uint32(10).string(message.ID);
    }
    if (message.Name !== "") {
      writer.uint32(18).string(message.Name);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RoleData {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoleData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Name = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoleData {
    return {
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
    };
  },

  toJSON(message: RoleData): unknown {
    const obj: any = {};
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.Name !== "") {
      obj.Name = message.Name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoleData>, I>>(base?: I): RoleData {
    return RoleData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoleData>, I>>(object: I): RoleData {
    const message = createBaseRoleData();
    message.ID = object.ID ?? "";
    message.Name = object.Name ?? "";
    return message;
  },
};

function createBaseGetRoleAuthRequest(): GetRoleAuthRequest {
  return { ID: undefined };
}

export const GetRoleAuthRequest = {
  encode(message: GetRoleAuthRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== undefined) {
      writer.uint32(10).string(message.ID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetRoleAuthRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRoleAuthRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRoleAuthRequest {
    return { ID: isSet(object.ID) ? globalThis.String(object.ID) : undefined };
  },

  toJSON(message: GetRoleAuthRequest): unknown {
    const obj: any = {};
    if (message.ID !== undefined) {
      obj.ID = message.ID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRoleAuthRequest>, I>>(base?: I): GetRoleAuthRequest {
    return GetRoleAuthRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRoleAuthRequest>, I>>(object: I): GetRoleAuthRequest {
    const message = createBaseGetRoleAuthRequest();
    message.ID = object.ID ?? undefined;
    return message;
  },
};

function createBaseGetRoleAuthResponse(): GetRoleAuthResponse {
  return { Page: undefined };
}

export const GetRoleAuthResponse = {
  encode(message: GetRoleAuthResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Page !== undefined) {
      Page.encode(message.Page, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetRoleAuthResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRoleAuthResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Page = Page.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRoleAuthResponse {
    return { Page: isSet(object.Page) ? Page.fromJSON(object.Page) : undefined };
  },

  toJSON(message: GetRoleAuthResponse): unknown {
    const obj: any = {};
    if (message.Page !== undefined) {
      obj.Page = Page.toJSON(message.Page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRoleAuthResponse>, I>>(base?: I): GetRoleAuthResponse {
    return GetRoleAuthResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRoleAuthResponse>, I>>(object: I): GetRoleAuthResponse {
    const message = createBaseGetRoleAuthResponse();
    message.Page = (object.Page !== undefined && object.Page !== null) ? Page.fromPartial(object.Page) : undefined;
    return message;
  },
};

function createBaseUpdateRoleRequest(): UpdateRoleRequest {
  return { ID: "", Name: "", Page: undefined };
}

export const UpdateRoleRequest = {
  encode(message: UpdateRoleRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== "") {
      writer.uint32(10).string(message.ID);
    }
    if (message.Name !== "") {
      writer.uint32(18).string(message.Name);
    }
    if (message.Page !== undefined) {
      Page.encode(message.Page, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UpdateRoleRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Page = Page.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateRoleRequest {
    return {
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
      Page: isSet(object.Page) ? Page.fromJSON(object.Page) : undefined,
    };
  },

  toJSON(message: UpdateRoleRequest): unknown {
    const obj: any = {};
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.Name !== "") {
      obj.Name = message.Name;
    }
    if (message.Page !== undefined) {
      obj.Page = Page.toJSON(message.Page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateRoleRequest>, I>>(base?: I): UpdateRoleRequest {
    return UpdateRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateRoleRequest>, I>>(object: I): UpdateRoleRequest {
    const message = createBaseUpdateRoleRequest();
    message.ID = object.ID ?? "";
    message.Name = object.Name ?? "";
    message.Page = (object.Page !== undefined && object.Page !== null) ? Page.fromPartial(object.Page) : undefined;
    return message;
  },
};

function createBaseDeleteRoleRequest(): DeleteRoleRequest {
  return { ID: "" };
}

export const DeleteRoleRequest = {
  encode(message: DeleteRoleRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== "") {
      writer.uint32(10).string(message.ID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeleteRoleRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteRoleRequest {
    return { ID: isSet(object.ID) ? globalThis.String(object.ID) : "" };
  },

  toJSON(message: DeleteRoleRequest): unknown {
    const obj: any = {};
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteRoleRequest>, I>>(base?: I): DeleteRoleRequest {
    return DeleteRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteRoleRequest>, I>>(object: I): DeleteRoleRequest {
    const message = createBaseDeleteRoleRequest();
    message.ID = object.ID ?? "";
    return message;
  },
};

function createBaseBindRoleRequest(): BindRoleRequest {
  return { AccountID: "", RoleID: "" };
}

export const BindRoleRequest = {
  encode(message: BindRoleRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AccountID !== "") {
      writer.uint32(10).string(message.AccountID);
    }
    if (message.RoleID !== "") {
      writer.uint32(18).string(message.RoleID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BindRoleRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBindRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.AccountID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.RoleID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BindRoleRequest {
    return {
      AccountID: isSet(object.AccountID) ? globalThis.String(object.AccountID) : "",
      RoleID: isSet(object.RoleID) ? globalThis.String(object.RoleID) : "",
    };
  },

  toJSON(message: BindRoleRequest): unknown {
    const obj: any = {};
    if (message.AccountID !== "") {
      obj.AccountID = message.AccountID;
    }
    if (message.RoleID !== "") {
      obj.RoleID = message.RoleID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BindRoleRequest>, I>>(base?: I): BindRoleRequest {
    return BindRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BindRoleRequest>, I>>(object: I): BindRoleRequest {
    const message = createBaseBindRoleRequest();
    message.AccountID = object.AccountID ?? "";
    message.RoleID = object.RoleID ?? "";
    return message;
  },
};

function createBaseUnBindRoleRequest(): UnBindRoleRequest {
  return { AccountID: "" };
}

export const UnBindRoleRequest = {
  encode(message: UnBindRoleRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AccountID !== "") {
      writer.uint32(10).string(message.AccountID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UnBindRoleRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnBindRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.AccountID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnBindRoleRequest {
    return { AccountID: isSet(object.AccountID) ? globalThis.String(object.AccountID) : "" };
  },

  toJSON(message: UnBindRoleRequest): unknown {
    const obj: any = {};
    if (message.AccountID !== "") {
      obj.AccountID = message.AccountID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnBindRoleRequest>, I>>(base?: I): UnBindRoleRequest {
    return UnBindRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnBindRoleRequest>, I>>(object: I): UnBindRoleRequest {
    const message = createBaseUnBindRoleRequest();
    message.AccountID = object.AccountID ?? "";
    return message;
  },
};

function createBaseLoginRequest(): LoginRequest {
  return { UserName: "", Password: "" };
}

export const LoginRequest = {
  encode(message: LoginRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.UserName !== "") {
      writer.uint32(10).string(message.UserName);
    }
    if (message.Password !== "") {
      writer.uint32(18).string(message.Password);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.UserName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Password = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRequest {
    return {
      UserName: isSet(object.UserName) ? globalThis.String(object.UserName) : "",
      Password: isSet(object.Password) ? globalThis.String(object.Password) : "",
    };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.UserName !== "") {
      obj.UserName = message.UserName;
    }
    if (message.Password !== "") {
      obj.Password = message.Password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(base?: I): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(object: I): LoginRequest {
    const message = createBaseLoginRequest();
    message.UserName = object.UserName ?? "";
    message.Password = object.Password ?? "";
    return message;
  },
};

function createBaseLoginResponse(): LoginResponse {
  return { SessionID: "", Role: undefined };
}

export const LoginResponse = {
  encode(message: LoginResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.SessionID !== "") {
      writer.uint32(10).string(message.SessionID);
    }
    if (message.Role !== undefined) {
      Role.encode(message.Role, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LoginResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.SessionID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Role = Role.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginResponse {
    return {
      SessionID: isSet(object.SessionID) ? globalThis.String(object.SessionID) : "",
      Role: isSet(object.Role) ? Role.fromJSON(object.Role) : undefined,
    };
  },

  toJSON(message: LoginResponse): unknown {
    const obj: any = {};
    if (message.SessionID !== "") {
      obj.SessionID = message.SessionID;
    }
    if (message.Role !== undefined) {
      obj.Role = Role.toJSON(message.Role);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginResponse>, I>>(base?: I): LoginResponse {
    return LoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResponse>, I>>(object: I): LoginResponse {
    const message = createBaseLoginResponse();
    message.SessionID = object.SessionID ?? "";
    message.Role = (object.Role !== undefined && object.Role !== null) ? Role.fromPartial(object.Role) : undefined;
    return message;
  },
};

function createBaseLogoutRequest(): LogoutRequest {
  return { SessionID: "" };
}

export const LogoutRequest = {
  encode(message: LogoutRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.SessionID !== "") {
      writer.uint32(10).string(message.SessionID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LogoutRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.SessionID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutRequest {
    return { SessionID: isSet(object.SessionID) ? globalThis.String(object.SessionID) : "" };
  },

  toJSON(message: LogoutRequest): unknown {
    const obj: any = {};
    if (message.SessionID !== "") {
      obj.SessionID = message.SessionID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutRequest>, I>>(base?: I): LogoutRequest {
    return LogoutRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutRequest>, I>>(object: I): LogoutRequest {
    const message = createBaseLogoutRequest();
    message.SessionID = object.SessionID ?? "";
    return message;
  },
};

export type MainService = typeof MainService;
export const MainService = {
  login: {
    path: "/proto.Main/Login",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: LoginRequest) => Buffer.from(LoginRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => LoginRequest.decode(value),
    responseSerialize: (value: LoginResponse) => Buffer.from(LoginResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => LoginResponse.decode(value),
  },
  logout: {
    path: "/proto.Main/Logout",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: LogoutRequest) => Buffer.from(LogoutRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => LogoutRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  createAccount: {
    path: "/proto.Main/CreateAccount",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateAccountRequest) => Buffer.from(CreateAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CreateAccountRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  listAccount: {
    path: "/proto.Main/ListAccount",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListAccountRequest) => Buffer.from(ListAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ListAccountRequest.decode(value),
    responseSerialize: (value: ListAccountResponse) => Buffer.from(ListAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ListAccountResponse.decode(value),
  },
  updateAccount: {
    path: "/proto.Main/UpdateAccount",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateAccountRequest) => Buffer.from(UpdateAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UpdateAccountRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  deleteAccount: {
    path: "/proto.Main/DeleteAccount",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteAccountRequest) => Buffer.from(DeleteAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DeleteAccountRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  deactiveAccount: {
    path: "/proto.Main/DeactiveAccount",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteAccountRequest) => Buffer.from(DeleteAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DeleteAccountRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  activeAccount: {
    path: "/proto.Main/ActiveAccount",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteAccountRequest) => Buffer.from(DeleteAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DeleteAccountRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  createRole: {
    path: "/proto.Main/CreateRole",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateRoleRequest) => Buffer.from(CreateRoleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CreateRoleRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  listRole: {
    path: "/proto.Main/ListRole",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListRoleRequest) => Buffer.from(ListRoleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ListRoleRequest.decode(value),
    responseSerialize: (value: ListRoleResponse) => Buffer.from(ListRoleResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ListRoleResponse.decode(value),
  },
  getRoleAuth: {
    path: "/proto.Main/GetRoleAuth",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetRoleAuthRequest) => Buffer.from(GetRoleAuthRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetRoleAuthRequest.decode(value),
    responseSerialize: (value: GetRoleAuthResponse) => Buffer.from(GetRoleAuthResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetRoleAuthResponse.decode(value),
  },
  updateRole: {
    path: "/proto.Main/UpdateRole",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateRoleRequest) => Buffer.from(UpdateRoleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UpdateRoleRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  deleteRole: {
    path: "/proto.Main/DeleteRole",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteRoleRequest) => Buffer.from(DeleteRoleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DeleteRoleRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  bindRole: {
    path: "/proto.Main/BindRole",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BindRoleRequest) => Buffer.from(BindRoleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => BindRoleRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  unBindRole: {
    path: "/proto.Main/UnBindRole",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UnBindRoleRequest) => Buffer.from(UnBindRoleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UnBindRoleRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface MainServer extends UntypedServiceImplementation {
  login: handleUnaryCall<LoginRequest, LoginResponse>;
  logout: handleUnaryCall<LogoutRequest, Empty>;
  createAccount: handleUnaryCall<CreateAccountRequest, Empty>;
  listAccount: handleUnaryCall<ListAccountRequest, ListAccountResponse>;
  updateAccount: handleUnaryCall<UpdateAccountRequest, Empty>;
  deleteAccount: handleUnaryCall<DeleteAccountRequest, Empty>;
  deactiveAccount: handleUnaryCall<DeleteAccountRequest, Empty>;
  activeAccount: handleUnaryCall<DeleteAccountRequest, Empty>;
  createRole: handleUnaryCall<CreateRoleRequest, Empty>;
  listRole: handleUnaryCall<ListRoleRequest, ListRoleResponse>;
  getRoleAuth: handleUnaryCall<GetRoleAuthRequest, GetRoleAuthResponse>;
  updateRole: handleUnaryCall<UpdateRoleRequest, Empty>;
  deleteRole: handleUnaryCall<DeleteRoleRequest, Empty>;
  bindRole: handleUnaryCall<BindRoleRequest, Empty>;
  unBindRole: handleUnaryCall<UnBindRoleRequest, Empty>;
}

export interface MainClient extends Client {
  login(
    request: LoginRequest,
    callback: (error: ServiceError | null, response: LoginResponse) => void,
  ): ClientUnaryCall;
  login(
    request: LoginRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: LoginResponse) => void,
  ): ClientUnaryCall;
  login(
    request: LoginRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: LoginResponse) => void,
  ): ClientUnaryCall;
  logout(request: LogoutRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  logout(
    request: LogoutRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  logout(
    request: LogoutRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  createAccount(
    request: CreateAccountRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  createAccount(
    request: CreateAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  createAccount(
    request: CreateAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  listAccount(
    request: ListAccountRequest,
    callback: (error: ServiceError | null, response: ListAccountResponse) => void,
  ): ClientUnaryCall;
  listAccount(
    request: ListAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListAccountResponse) => void,
  ): ClientUnaryCall;
  listAccount(
    request: ListAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListAccountResponse) => void,
  ): ClientUnaryCall;
  updateAccount(
    request: UpdateAccountRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  updateAccount(
    request: UpdateAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  updateAccount(
    request: UpdateAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteAccount(
    request: DeleteAccountRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteAccount(
    request: DeleteAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteAccount(
    request: DeleteAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deactiveAccount(
    request: DeleteAccountRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deactiveAccount(
    request: DeleteAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deactiveAccount(
    request: DeleteAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  activeAccount(
    request: DeleteAccountRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  activeAccount(
    request: DeleteAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  activeAccount(
    request: DeleteAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  createRole(
    request: CreateRoleRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  createRole(
    request: CreateRoleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  createRole(
    request: CreateRoleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  listRole(
    request: ListRoleRequest,
    callback: (error: ServiceError | null, response: ListRoleResponse) => void,
  ): ClientUnaryCall;
  listRole(
    request: ListRoleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListRoleResponse) => void,
  ): ClientUnaryCall;
  listRole(
    request: ListRoleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListRoleResponse) => void,
  ): ClientUnaryCall;
  getRoleAuth(
    request: GetRoleAuthRequest,
    callback: (error: ServiceError | null, response: GetRoleAuthResponse) => void,
  ): ClientUnaryCall;
  getRoleAuth(
    request: GetRoleAuthRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetRoleAuthResponse) => void,
  ): ClientUnaryCall;
  getRoleAuth(
    request: GetRoleAuthRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetRoleAuthResponse) => void,
  ): ClientUnaryCall;
  updateRole(
    request: UpdateRoleRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  updateRole(
    request: UpdateRoleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  updateRole(
    request: UpdateRoleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteRole(
    request: DeleteRoleRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteRole(
    request: DeleteRoleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteRole(
    request: DeleteRoleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  bindRole(request: BindRoleRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  bindRole(
    request: BindRoleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  bindRole(
    request: BindRoleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  unBindRole(
    request: UnBindRoleRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  unBindRole(
    request: UnBindRoleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  unBindRole(
    request: UnBindRoleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const MainClient = makeGenericClientConstructor(MainService, "proto.Main") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MainClient;
  service: typeof MainService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
