// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file account.proto (package api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAccountRequest, Empty } from "./account_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.Account
 */
export const Account = {
  typeName: "api.Account",
  methods: {
    /**
     * rpc ListAccount(ListAccountRequest) returns (google.protobuf.Empty);
     * rpc UpdateAccount(UpdateAccountRequest) returns (google.protobuf.Empty);
     * rpc DeleteAccount(DeleteAccountRequest) returns (google.protobuf.Empty);
     * rpc InactiveAccount(InactiveAccountRequest) returns (google.protobuf.Empty);
     * rpc ActiveAccount(ActiveAccountRequest) returns (google.protobuf.Empty);
     *
     * @generated from rpc api.Account.CreateAccount
     */
    createAccount: {
      name: "CreateAccount",
      I: CreateAccountRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

